global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'interview-cv-tracking-system'
    static_configs:
      - targets: ['cv-tracker:9464']
    metrics_path: '/metrics' 